# Configurações do KabanaPrisao

# Database
Database:
  Type: "SQLITE" # [SQLITE, MYSQL]
  Sqlite:
    Filename: "database.db"
  Host: "localhost:3306"
  Database: "kabana"
  User: "root"
  Password: "143010"

# Gerais

# Mandar mensagem para todos quando um jogador for preso
AlertaJogadorPreso: true
# Mandar mensagem para todos quando um jogador for solto
AlertaJogadorSolto: true
# Mandar mensagem para todos quando um preso entrar no servidor
AlertaPresoEntrou: true
# Mandar mensagem para todos quando um preso sair no servidor
AlertaPresoSaiu: true

# Mandar mensagem para todos quando um jogador pagar a fiança
AlertaPagouFianca: true

# Se 'true' o tempo de prisão dos jogadores vão diminuir somente se eles estiverem online
DiminuirTempoOnline: true

# Bloquear todos os comandos para um jogador preso
BloquearTodosComandos: false

# Chave para permitir ou bloquear comandos de um jogador preso
# 'permitir' ⇒ Usar a lista de comandos permitidos
# 'negar' ⇒ Usar a lista de comandos bloqueados

PermitirOuNegar: 'permitir'

# Se um jogador tiver essa permissão, a regra de bloquear comandos não valerá para ele
PermissaoIgnorarRegraComandos: 'kabanaprisao.commands.bypass'

# Comandos permitidos para jogadores presos
ComandosPermitidos:
  - '/prision'
  - '/prisao'
  - '/prisioninfo'
  - '/prisaoinfo'
  - '/infoprisao'
  - '/money'

# Comandos bloqueados para jogadores presos
ComandosBloqueados:
  - '/spawn'

# Mensagens de status dos menus

